# Generated by Django 4.2.17 on 2025-04-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Spanish")],
                default="en",
                max_length=4,
            ),
        ),
    ]
