# Generated by Django 4.2.17 on 2025-01-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Custom configuration for the feature in this plan",
                        null=True,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="features.feature",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "unique_together": {("plan", "feature")},
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.ManyToManyField(
                related_name="plans",
                through="subscriptions.PlanFeature",
                to="features.feature",
            ),
        ),
    ]
