# Generated by Django 4.2.17 on 2025-01-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
        ("subscriptions", "0002_planfeature_plan_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfeature",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_plans",
                to="features.feature",
            ),
        ),
        migrations.AlterField(
            model_name="planfeature",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_features",
                to="subscriptions.plan",
            ),
        ),
    ]
