# Generated by Django 4.2.17 on 2025-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_subscription_billing_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
