# Generated by Django 4.2.17 on 2025-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_subscription_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.JSONField(default=dict),
        ),
    ]
