# Generated by Django 4.2.17 on 2025-06-15 14:40

from django.db import migrations

def create_free_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    try:
        plan = Plan.objects.filter(is_free=True).first()

        if not plan:
            Plan.objects.create(
                name={
                    "en": "Basic",
                    "es": "Básico",
                },
                description={
                    "en": "Ideal for individuals who want to get started with essential features — free forever.",
                    "es": "Ideal para personas que quieren comenzar con las funciones esenciales — gratis para siempre.",
                },
                monthly_price=0,
                yearly_price=0,
                is_free=True,
                stripe_price_id=None,
            )
    except Exception as e:
        raise RuntimeError(f"create_free_plan failed: {str(e)}")


def delete_free_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Plan.objects.filter(is_free=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_plan_is_free"),
    ]

    operations = [
        migrations.RunPython(create_free_plan, delete_free_plan)
    ]
