# Generated by Django 4.2.17 on 2025-06-15 15:27

from django.db import migrations

from apps.features.choices.feature_code_choices import FeatureCodeChoices


def assign_basic_features_to_free_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Feature = apps.get_model("features", "Feature")
    PlanFeature = apps.get_model("subscriptions", "PlanFeature")

    try:
        free_plan = Plan.objects.get(is_free=True)
    except Plan.DoesNotExist:
        raise RuntimeError("Free Plan does not exist. Cannot assign features.")

    feature_codes = [
        FeatureCodeChoices.CLOUD_STORAGE.value,
        FeatureCodeChoices.FILE_PREVIEW.value,
        FeatureCodeChoices.FILE_SHARING.value,
        FeatureCodeChoices.FOLDER_CREATION.value,
        FeatureCodeChoices.BASIC_SUPPORT.value,
    ]

    features = Feature.objects.filter(code__in=feature_codes)

    for feature in features:
        PlanFeature.objects.update_or_create(
            plan=free_plan,
            feature=feature,
            defaults={"metadata": feature.metadata or {}},
        )


def unassign_basic_features_from_free_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    PlanFeature = apps.get_model("subscriptions", "PlanFeature")

    try:
        free_plan = Plan.objects.get(is_free=True)
    except Plan.DoesNotExist:
        return

    feature_codes = [
        FeatureCodeChoices.CLOUD_STORAGE.value,
        FeatureCodeChoices.FILE_PREVIEW.value,
        FeatureCodeChoices.FILE_SHARING.value,
        FeatureCodeChoices.FOLDER_CREATION.value,
        FeatureCodeChoices.BASIC_SUPPORT.value,
    ]

    PlanFeature.objects.filter(
        plan=free_plan,
        feature__code__in=feature_codes
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_create_basic_plan"),
        ("features", "0004_create_basic_features"),
    ]

    operations = [
        migrations.RunPython(assign_basic_features_to_free_plan, unassign_basic_features_from_free_plan)
    ]
