# Generated by Django 4.2.17 on 2025-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_assign_features_to_basic_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("past_due", "Past Due"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
