# Generated by Django 4.2.17 on 2025-07-03 14:01

from django.db import migrations


def create_pro_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")

    try:
        plan = Plan.objects.filter(name__en="Pro", is_free=False).exists()

        if not plan:
            Plan.objects.create(
                name={
                    "en": "Pro",
                    "es": "Profesional",
                },
                description={
                    "en": "	Designed for professionals who need more storage, sharing, and support.",
                    "es": "Diseñado para profesionales que necesitan más almacenamiento, opciones de compartición y soporte.",
                },
                monthly_price=4.99,
                yearly_price=0,
                is_free=False,
                stripe_price_id="1234",
            )
    except Exception as e:
        raise RuntimeError(f"create_pro_plan failed: {str(e)}")


def delete_pro_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Plan.objects.filter(name__en="Pro", is_free=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0012_alter_subscription_status"),
    ]

    operations = [migrations.RunPython(create_pro_plan, delete_pro_plan)]
