# Generated by Django 4.2.17 on 2025-07-03 14:11

from django.db import migrations

from apps.features.choices.feature_code_choices import FeatureCodeChoices


def assign_basic_features_to_pro_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Feature = apps.get_model("features", "Feature")
    PlanFeature = apps.get_model("subscriptions", "PlanFeature")

    try:
        pro_plan = Plan.objects.get(name__en="Pro", is_free=False)
    except Plan.DoesNotExist:
        raise RuntimeError("Free Plan does not exist. Cannot assign features.")

    feature_codes = [
        FeatureCodeChoices.CLOUD_STORAGE.value,
        FeatureCodeChoices.FILE_PREVIEW.value,
        FeatureCodeChoices.FILE_SHARING.value,
        FeatureCodeChoices.FOLDER_CREATION.value,
        FeatureCodeChoices.BASIC_SUPPORT.value,
    ]

    features = Feature.objects.filter(code__in=feature_codes)

    for feature in features:
        metadata = {}
        if feature.code == FeatureCodeChoices.CLOUD_STORAGE.value:
            metadata = {
                "max_storage_mb": 50000,
                "max_file_size_mb": 2000,
                "blocked_file_types": [
                    "exe", "dll", "msi", "sh", "bat", "cmd", "com", "pif", "jar", "class",
                    "vb", "vbs", "apk", "iso", "img", "scr", "hta", "gadget", "wsf"
                ]
            }
        elif feature.code == FeatureCodeChoices.FILE_SHARING.value:
            metadata = {
                "allow_folder_sharing": True,
                "allow_password": True,
                "allow_choose_expiration": True,
                "max_expiration_minutes": None,
                "max_active_links": 50,
                "allow_custom_message": True
            }

        PlanFeature.objects.update_or_create(
            plan=pro_plan,
            feature=feature,
            defaults={"metadata": metadata or {}},
        )


def unassign_basic_features_from_pro_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    PlanFeature = apps.get_model("subscriptions", "PlanFeature")

    try:
        pro_plan = Plan.objects.get(name__en="Pro", is_free=True)
    except Plan.DoesNotExist:
        return

    feature_codes = [
        FeatureCodeChoices.CLOUD_STORAGE.value,
        FeatureCodeChoices.FILE_PREVIEW.value,
        FeatureCodeChoices.FILE_SHARING.value,
        FeatureCodeChoices.FOLDER_CREATION.value,
        FeatureCodeChoices.BASIC_SUPPORT.value,
    ]

    PlanFeature.objects.filter(
        plan=pro_plan,
        feature__code__in=feature_codes
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0013_create_pro_plan"),
        ("features", "0004_create_basic_features"),
    ]

    operations = [
        migrations.RunPython(assign_basic_features_to_pro_plan, unassign_basic_features_from_pro_plan)
    ]
