# Generated by Django 4.2.17 on 2025-07-03 14:17

from django.db import migrations


def create_enterprise_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")

    try:
        plan = Plan.objects.filter(name__en="Enterprise", is_free=False).exists()

        if not plan:
            Plan.objects.create(
                name={
                    "en": "Enterprise",
                    "es": "Empresas",
                },
                description={
                    "en": "Perfect for teams or organizations that need advanced features, security, and priority support.",
                    "es": "Perfecto para equipos u organizaciones que necesitan funciones avanzadas, seguridad y soporte prioritario.",
                },
                monthly_price=99.99,
                yearly_price=0,
                is_free=False,
                stripe_price_id="1122",
            )
    except Exception as e:
        raise RuntimeError(f"create_enterprise_plan failed: {str(e)}")


def delete_enterprise_plan(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Plan.objects.filter(name__en="Enterprise", is_free=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0014_assign_features_to_pro_plan"),
    ]

    operations = [migrations.RunPython(create_enterprise_plan, delete_enterprise_plan)]
