# Generated by Django 4.2.17 on 2025-02-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Credit Card"), ("paypal", "PayPal")], max_length=50
            ),
        ),
    ]
