# Generated by Django 4.2.17 on 2025-02-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Credit Card"), ("paypal", "PayPal")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled (Void)"),
                ],
                max_length=20,
            ),
        ),
    ]
