# Generated by Django 4.2.17 on 2025-02-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="invoice_pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_invoice_id",
            field=models.CharField(max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
