# Generated by Django 4.2.17 on 2025-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_invoice_pdf_url_payment_invoice_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the payment was made.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("card", "Credit Card"), ("paypal", "PayPal")],
                max_length=10,
                null=True,
            ),
        ),
    ]
