# Generated by Django 4.2.17 on 2025-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("eur", "Euro")], default="eur", max_length=3
            ),
        ),
    ]
