# Generated by Django 4.2.17 on 2025-03-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_payment_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled (Void)"),
                    ("retrying", "Retrying"),
                ],
                max_length=20,
            ),
        ),
    ]
