# Generated by Django 4.2.17 on 2025-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[("cloud_storage", "Cloud Storage")],
                        help_text="Unique identifier for the feature",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Optional: store feature-specific config",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
