# Generated by Django 4.2.17 on 2025-03-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="code",
            field=models.CharField(
                choices=[
                    ("cloud_storage", "Cloud Storage"),
                    ("file_preview", "File Preview"),
                    ("file_sharing", "File Sharing via Link"),
                    ("folder_creation", "Folder Creation"),
                    ("basic_support", "Basic Email Support"),
                ],
                help_text="Unique identifier for the feature",
                max_length=50,
                unique=True,
            ),
        ),
    ]
