# Generated by Django 4.2.17 on 2025-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_alter_feature_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.JSONField(default=dict),
        ),
    ]
