# Generated by Django 4.2.17 on 2025-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="The current status of the file upload process.",
                max_length=8,
            ),
        ),
    ]
