# Generated by Django 4.2.15 on 2024-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cloudfiles",
            name="cloud_stora_name_617d94_idx",
        ),
        migrations.RenameField(
            model_name="cloudfiles",
            old_name="name",
            new_name="file_name",
        ),
        migrations.AlterUniqueTogether(
            name="cloudfiles",
            unique_together={("path", "file_name")},
        ),
        migrations.AddIndex(
            model_name="cloudfiles",
            index=models.Index(
                fields=["file_name"], name="cloud_stora_file_na_cdabf4_idx"
            ),
        ),
    ]
