# Generated by Django 4.2.17 on 2025-01-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0002_alter_cloudfile_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudfile",
            name="file_url",
        ),
    ]
