# Generated by Django 4.2.17 on 2025-01-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0003_remove_cloudfile_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudfile",
            name="path",
            field=models.CharField(
                help_text="The S3 path where the file is stored.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
