# Generated by Django 4.2.17 on 2025-01-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0004_alter_cloudfile_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudfile",
            name="checksum",
        ),
    ]
