# Generated by Django 4.2.17 on 2025-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_storage", "0005_remove_cloudfile_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
