# Generated by Django 4.2.17 on 2025-04-17 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud_storage", "0007_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfile",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="cloud_storage.folder",
            ),
        ),
    ]
