# Generated by Django 4.2.17 on 2025-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud_storage", "0008_cloudfile_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfile",
            name="s3_key",
            field=models.CharField(
                blank=True,
                help_text="Full S3 object key path",
                max_length=1024,
                null=True,
                unique=True,
            ),
        ),
    ]
