# Generated by Django 4.2.24 on 2025-11-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud_storage", "0010_alter_cloudfile_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudfile",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("file_not_found_in_s3", "File not found in S3"),
                    ("storage_quota_exceeded", "Storage quota exceeded"),
                    ("file_too_large", "File too large for plan"),
                    ("unknown_s3_error", "Unknown S3 error"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
