# Generated by Django 4.2.24 on 2025-11-27 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.cloud_storage.models.share_link


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cloud_storage", "0011_cloudfile_error_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.cloud_storage.models.share_link.generate_share_token,
                        help_text="Public token used to identify the shared link.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the link will automatically expire.",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the user manually deactivated this link.",
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Hashed password required to access this link, if enabled.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Files included in this shared link.",
                        related_name="share_links",
                        to="cloud_storage.cloudfile",
                    ),
                ),
                (
                    "folders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Folders included in this shared link.",
                        related_name="share_links",
                        to="cloud_storage.folder",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="sharelink_owner_created_idx",
                    )
                ],
            },
        ),
    ]
