# Generated by Django 4.2.24 on 2026-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud_storage", "0012_sharelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudfile",
            name="path",
            field=models.CharField(
                help_text="The path where the file is stored.", max_length=255
            ),
        ),
    ]
